import { API } from '../config';
// temporary global data so we don't need to query the API while creating styles
const tempData = [ { id: 112305,
            title: 'Chicken Samlá (Cambodian Chicken Curry)',
            readyInMinutes: 45,
            image: 'chicken-saml-cambodian-chicken-curry-112305.jpg',
            imageUrls: [ 'chicken-saml-cambodian-chicken-curry-112305.jpg' ] },
          { id: 472214,
            title: 'Chicken Chicken Curry',
            readyInMinutes: 85,
            image: 'Chicken-Chicken-Curry-472214.jpg',
            imageUrls: [ 'Chicken-Chicken-Curry-472214.jpg' ] },
          { id: 17816,
            title: 'Chicken Potstickers',
            readyInMinutes: 19,
            image: 'chicken-potstickers-2-17816.jpg',
            imageUrls: [ 'chicken-potstickers-2-17816.jpg' ] },
          { id: 32068,
            title: 'Chicken Curry',
            readyInMinutes: 33,
            image: 'chicken-curry-2-32068.jpg',
            imageUrls: [ 'chicken-curry-2-32068.jpg' ] },
          { id: 39180,
            title: 'Chicken Ramen',
            readyInMinutes: 64,
            image: 'chicken_ramen-39180.jpg',
            imageUrls: [ 'chicken_ramen-39180.jpg', 'chicken-ramen-2-39180.jpg' ] },
          { id: 74396,
            title: 'Tandoori Chicken',
            readyInMinutes: 45,
            image: 'tandoori-chicken-74396.jpg',
            imageUrls: [ 'tandoori-chicken-74396.jpg' ] },
          { id: 83200,
            title: 'Chicken Curry',
            readyInMinutes: 100,
            image: 'chicken_curry-83200.jpg',
            imageUrls: [ 'chicken_curry-83200.jpg', 'chicken-curry-2-83200.jpg' ] },
          { id: 136526,
            title: 'Chicken Curry',
            readyInMinutes: 45,
            image: 'chicken-curry-2-136526.png',
            imageUrls: [ 'chicken-curry-2-136526.png', 'chicken_curry-136526.jpg' ] },
          { id: 137102,
            title: 'Butter Chicken',
            readyInMinutes: 70,
            image: 'butter-chicken-2-137102.jpg',
            imageUrls: [ 'butter-chicken-2-137102.jpg', 'butter_chicken-137102.jpg' ] },
          { id: 152697,
            title: 'Chicken Vindaloo',
            readyInMinutes: 45,
            image: 'chicken-vindaloo-152697.jpg',
            imageUrls: [ 'chicken-vindaloo-152697.jpg' ] } ];
const tempBaseUri = "https://spoonacular.com/recipeImages/";

export function getSearchResults(query) {
  // comment out real API call to use temp data for now
  /*let url = API.uri + '/recipes/search?cuisine=Asian&intolerances=corn&limitLicense=false&number=10&offset=0&query=' + query,
      request = new Request(url, {
        headers: new Headers({
          'X-Mashape-Key': API.key,
          //'Accept': 'application/json'
        })
      });
  fetch(request)
    .then((res) => res.json())
    .then((data) => {
      let recipeList = this.state.dataSource.cloneWithRows(data.results);
      console.log(recipeList);
    })
    .catch((error) => console.log("Oops, there was a problem:", error));*/

  // temp styling code
  setTimeout(() => {
    let recipeList = this.state.dataSource.cloneWithRows(tempData);
    this.props.navigator.push({
      title: 'Results',
      index: 1,
      passProps: {
        data: recipeList,
        baseUri: tempBaseUri
      }
    });
  }, 100);
}

const tempRecipe = { vegetarian: false,
  vegan: false,
  glutenFree: true,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  weightWatcherSmartPoints: 6,
  gaps: 'no',
  lowFodmap: false,
  ketogenic: false,
  whole30: false,
  servings: 6,
  preparationMinutes: 15,
  cookingMinutes: 70,
  sourceUrl: 'http://allrecipes.com/Recipe/Chicken-Chicken-Curry/Detail.aspx?src=rss',
  spoonacularSourceUrl: 'https://spoonacular.com/chicken-chicken-curry-472214',
  aggregateLikes: 37,
  creditText: 'Allrecipes',
  sourceName: 'Allrecipes',
  extendedIngredients:
   [ { id: 2004,
       aisle: 'Spices and Seasonings',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/bay-leaves.jpg',
       name: 'bay leaf',
       amount: 1,
       unit: '',
       unitShort: '',
       unitLong: '',
       originalString: '1 bay leaf',
       metaInformation: [] },
     { id: 1002006,
       aisle: 'Spices and Seasonings',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/cardamom.jpg',
       name: 'cardamom pods',
       amount: 3,
       unit: '',
       unitShort: '',
       unitLong: '',
       originalString: '3 cardamom pods, lightly crushed',
       metaInformation: [ 'crushed' ] },
     { id: 2009,
       aisle: 'Spices and Seasonings',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/chili-powder.jpg',
       name: 'chili powder',
       amount: 0.5,
       unit: 'teaspoon',
       unitShort: 't',
       unitLong: 'teaspoons',
       originalString: '1/2 teaspoon chili powder',
       metaInformation: [] },
     { id: 11165,
       aisle: 'Produce',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/cilantro.png',
       name: 'cilantro',
       amount: 1,
       unit: 'bunch',
       unitShort: 'bunch',
       unitLong: 'bunch',
       originalString: '1 bunch cilantro, chopped',
       metaInformation: [ 'chopped' ] },
     { id: 1002010,
       aisle: 'Spices and Seasonings',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/cinnamon.jpg',
       name: 'cinnamon stick',
       amount: 1,
       unit: 'stick',
       unitShort: 'stick',
       unitLong: 'stick',
       originalString: '1 (2 inch) cinnamon stick',
       metaInformation: [ '(2 inch)' ] },
     { id: 11215,
       aisle: 'Produce',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/garlic.jpg',
       name: 'garlic',
       amount: 2,
       unit: 'tablespoons',
       unitShort: 'T',
       unitLong: 'tablespoons',
       originalString: '2 tablespoons minced garlic',
       metaInformation: [ 'minced' ] },
     { id: 93632,
       aisle: 'Ethnic Foods',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/ghee.jpg',
       name: 'ghee',
       amount: 1,
       unit: 'tablespoon',
       unitShort: 'T',
       unitLong: 'tablespoon',
       originalString: '1 tablespoon ghee (clarified butter)',
       metaInformation: [ '(clarified butter)' ] },
     { id: 2012,
       aisle: 'Spices and Seasonings',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/ground-coriander.jpg',
       name: 'ground coriander',
       amount: 1,
       unit: 'tablespoon',
       unitShort: 'T',
       unitLong: 'tablespoon',
       originalString: '1 tablespoon ground coriander',
       metaInformation: [] },
     { id: 2021,
       aisle: 'Spices and Seasonings',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/ginger.jpg',
       name: 'ground ginger',
       amount: 2,
       unit: 'tablespoons',
       unitShort: 'T',
       unitLong: 'tablespoons',
       originalString: '2 tablespoons ground ginger',
       metaInformation: [] },
     { id: 2043,
       aisle: 'Spices and Seasonings',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/turmeric.jpg',
       name: 'ground turmeric',
       amount: 1,
       unit: 'tablespoon',
       unitShort: 'T',
       unitLong: 'tablespoon',
       originalString: '1 tablespoon ground turmeric',
       metaInformation: [] },
     { id: 4053,
       aisle: 'Oil, Vinegar, Salad Dressing',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/olive-oil.jpg',
       name: 'olive oil',
       amount: 3,
       unit: 'tablespoons',
       unitShort: 'T',
       unitLong: 'tablespoons',
       originalString: '3 tablespoons olive oil',
       metaInformation: [] },
     { id: 2028,
       aisle: 'Spices and Seasonings',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/chili-powder.jpg',
       name: 'paprika',
       amount: 0.5,
       unit: 'teaspoon',
       unitShort: 't',
       unitLong: 'teaspoons',
       originalString: '1/2 teaspoon paprika',
       metaInformation: [] },
     { id: 10011282,
       aisle: 'Produce',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/red-onion.jpg',
       name: 'red onion',
       amount: 1,
       unit: '',
       unitShort: '',
       unitLong: '',
       originalString: '1 red onion, thinly sliced, divided',
       metaInformation: [ 'red', 'divided', 'thinly sliced' ] },
     { id: 2047,
       aisle: 'Spices and Seasonings',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/salt.jpg',
       name: 'salt',
       amount: 6,
       unit: 'servings',
       unitShort: 'servings',
       unitLong: 'servings',
       originalString: 'salt to taste',
       metaInformation: [ 'to taste' ] },
     { id: 1055062,
       aisle: 'Meat',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/chicken-breasts.jpg',
       name: 'skinless boneless chicken breast',
       amount: 2.25,
       unit: 'pounds',
       unitShort: 'lb',
       unitLong: 'pounds',
       originalString: '2 1/4 pounds skinless, boneless chicken breast, cut in bite-sized pieces',
       metaInformation: [ 'boneless', 'skinless', 'cut in bite-sized pieces' ] },
     { id: 11529,
       aisle: 'Produce',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/tomatoes-canned.jpg',
       name: 'tomato',
       amount: 1,
       unit: '',
       unitShort: '',
       unitLong: '',
       originalString: '1 tomato, thinly sliced',
       metaInformation: [ 'thinly sliced' ] },
     { id: 14412,
       aisle: 'Beverages',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/water.jpg',
       name: 'water',
       amount: 1,
       unit: 'tablespoon',
       unitShort: 'T',
       unitLong: 'tablespoon',
       originalString: '1 tablespoon water',
       metaInformation: [] },
     { id: 19335,
       aisle: 'Baking',
       image: 'https://spoonacular.com/cdn/ingredients_100x100/sugar-cubes.jpg',
       name: 'white sugar',
       amount: 0.25,
       unit: 'teaspoon',
       unitShort: 't',
       unitLong: 'teaspoons',
       originalString: '1/4 teaspoon white sugar',
       metaInformation: [ 'white' ] } ],
  id: 472214,
  title: 'Chicken Chicken Curry',
  readyInMinutes: 85,
  image: 'https://spoonacular.com/recipeImages/Chicken-Chicken-Curry-472214.jpg',
  imageType: 'jpg',
  cuisines: [ 'asian', 'indian' ],
  instructions: 'Heat the olive oil in a skillet over high heat. Stir in 1/3 of the onion; cook and stir until the onion is golden brown and crisp, about 5 minutes. Season with salt. Remove the onion from the oil and drain on a paper towel-lined plate. Set aside.                            Place the remaining 2/3 of onion and the bay leaf into the same skillet over high heat. Cook and stir until the onion has turned golden brown, about 5 minutes. Stir in 1 tablespoon of water, then add the turmeric, chili powder, paprika, ginger, and garlic. Reduce heat to medium-high and continue to cook and stir until the liquid has reduced, then stir in another tablespoon of water.                            Place the chicken and tomato slices into the onion mixture. Season with salt and sugar. Stir in the cardamom pods, cloves, cinnamon stick, ghee, and 1 tablespoon of water. Cover and simmer on low until the liquid has reduced,  30 to 35 minutes. Stir in the coriander. Simmer until the liquid has evaporated. Sprinkle with cilantro and reserved fried onions before serving.                                                Kitchen-Friendly View' };

export function getRecipe(id) {
  // using temp recipe for styling
  /*let url = API.uri + `/recipes/${id}/information?includeNutrition=false`,
      request = new Request(url, {
        headers: new Headers({
          'X-Mashape-Key': API.key,
          'Accept': 'application/json'
        })
      });
  console.log('url is', url);
  fetch(request)
    .then((res) => res.json())
    .then((data) => {
      console.log(data);
      this.props.navigator.push({
        title: 'Recipe Card',
        index: 2,
        passProps: {
          data: data
        }
      });
    });*/
  // temp styling code
  setTimeout(() => {
    this.props.navigator.push({
      title: 'Recipe Card',
      index: 2,
      passProps: {
        data: tempRecipe,
      }
    });
  }, 100);
}
